#### 1.Impoort Liberies

In [25]:
import numpy as np
import pandas as pd

#### 2.Load the Dataset

In [26]:
df = dataset = pd.read_csv(r'C:\Users\hp\Downloads\retailhive_10k.csv')
df.head()

,product_title,rating,transaction_id,date,channel,region,customer_id,quantity,price,revenue
0,The Dirty Little Secrets of Getting Your Dream...,Four,1,2020-05-02,Store,US,13068,3,35.370401,106.111202
1,Mesaerion: The Best Science Fiction Stories 18...,One,2,2025-07-20,Online,Asia,40027,4,32.506908,130.027634
2,Libertarianism for Beginners,Two,3,2024-07-30,Online,US,40294,3,47.085821,141.257464
3,On a Midnight Clear,Three,4,2020-04-08,Mobile,US,19924,3,14.811784,44.435351
4,Online Marketing for Busy Authors: A Step-By-S...,One,5,2024-09-27,Mobile,Europe,40383,3,51.179701,153.539102

In [27]:
df.describe()

       transaction_id   customer_id      quantity         price       revenue
count     12000.00000  12000.000000  12000.000000  12000.000000  12000.000000
mean       6000.50000  30155.073083      2.975250     34.731508    103.383174
std        3464.24595  11501.173351      1.411726     15.201040     70.156603
min           1.00000  10000.000000      1.000000      8.136418      8.343938
25%        3000.75000  20202.750000      2.000000     20.499012     47.803286
50%        6000.50000  30259.000000      3.000000     34.441834     85.475147
75%        9000.25000  40201.500000      4.000000     47.102572    144.709868
max       12000.00000  49996.000000      5.000000     69.707900    344.725460

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_title   12000 non-null  object
 1   rating          12000 non-null  object
 2   transaction_id  12000 non-null  int64
 3   date            12000 non-null  object
 4   channel         12000 non-null  object
 5   region          12000 non-null  object
 6   customer_id     12000 non-null  int64
 7   quantity        12000 non-null  int64
 8   price           12000 non-null  float64
 9   revenue         12000 non-null  float64
dtypes: float64(2), int64(3), object(5)
memory usage: 937.6+ KB

#### 3.Remove Duplicates

In [29]:
df=df.drop_duplicates()

In [30]:
df.head()

,product_title,rating,transaction_id,date,channel,region,customer_id,quantity,price,revenue
0,The Dirty Little Secrets of Getting Your Dream...,Four,1,2020-05-02,Store,US,13068,3,35.370401,106.111202
1,Mesaerion: The Best Science Fiction Stories 18...,One,2,2025-07-20,Online,Asia,40027,4,32.506908,130.027634
2,Libertarianism for Beginners,Two,3,2024-07-30,Online,US,40294,3,47.085821,141.257464
3,On a Midnight Clear,Three,4,2020-04-08,Mobile,US,19924,3,14.811784,44.435351
4,Online Marketing for Busy Authors: A Step-By-S...,One,5,2024-09-27,Mobile,Europe,40383,3,51.179701,153.539102

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_title   12000 non-null  object
 1   rating          12000 non-null  object
 2   transaction_id  12000 non-null  int64
 3   date            12000 non-null  object
 4   channel         12000 non-null  object
 5   region          12000 non-null  object
 6   customer_id     12000 non-null  int64
 7   quantity        12000 non-null  int64
 8   price           12000 non-null  float64
 9   revenue         12000 non-null  float64
dtypes: float64(2), int64(3), object(5)
memory usage: 937.6+ KB

#### 4.Standardising the date formates

In [32]:
df['date']=pd.to_datetime(df['date'])

In [33]:
print(df['date'].head())

0   2020-05-02
1   2025-07-20
2   2024-07-30
3   2020-04-08
4   2024-09-27
Name: date, dtype: datetime64[ns]

In [34]:
df.dtypes

product_title             object
rating                    object
transaction_id             int64
date              datetime64[ns]
channel                   object
region                    object
customer_id                int64
quantity                   int64
price                    float64
revenue                  float64
dtype: object

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_title   12000 non-null  object
 1   rating          12000 non-null  object
 2   transaction_id  12000 non-null  int64
 3   date            12000 non-null  datetime64[ns]
 4   channel         12000 non-null  object
 5   region          12000 non-null  object
 6   customer_id     12000 non-null  int64
 7   quantity        12000 non-null  int64
 8   price           12000 non-null  float64
 9   revenue         12000 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(3), object(4)
memory usage: 937.6+ KB

#### 5.Save Clean Data

In [36]:
df.to_csv('cleaned_dataset.csv',index=False)